from __future__ import annotations

import argparse
import json
from pathlib import Path

from docs_chatbot_service.core.chunking import ChunkingConfig, split_text_into_word_chunks


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Chunk normalized docs into retrieval units.")
    parser.add_argument(
        "--docs-path",
        default="data/processed/docs.json",
        help="Path to normalized docs JSON generated by ingest.py.",
    )
    parser.add_argument(
        "--output-path",
        default="data/processed/chunks.json",
        help="Output chunk JSON path.",
    )
    parser.add_argument("--chunk-size-words", type=int, default=450)
    parser.add_argument("--overlap-words", type=int, default=70)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    docs_path = Path(args.docs_path)
    output_path = Path(args.output_path)

    if not docs_path.exists():
        raise FileNotFoundError(f"Docs file not found: {docs_path}")

    docs = json.loads(docs_path.read_text(encoding="utf-8"))
    if not isinstance(docs, list):
        raise ValueError("Docs JSON must be an array.")

    config = ChunkingConfig(
        chunk_size_words=args.chunk_size_words,
        overlap_words=args.overlap_words,
    )
    chunks: list[dict] = []
    chunk_count = 0

    for doc in docs:
        doc_id = str(doc["doc_id"])
        title = str(doc.get("title", doc_id))
        section = str(doc.get("section", "general"))
        source = str(doc.get("source", ""))
        text = str(doc.get("text", ""))

        for index, chunk_text in enumerate(split_text_into_word_chunks(text=text, config=config), start=1):
            chunk_count += 1
            chunks.append(
                {
                    "chunk_id": f"{doc_id}-{index}",
                    "doc_id": doc_id,
                    "title": title,
                    "section": section,
                    "source": source,
                    "text": chunk_text,
                }
            )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(chunks, ensure_ascii=True, indent=2), encoding="utf-8")
    print(f"Generated {chunk_count} chunks into: {output_path}")


if __name__ == "__main__":
    main()
